# Generated by Django 4.2.1 on 2023-05-23 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='답변 내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일지')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='최종 수정 일지')),
            ],
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='질문 제목')),
                ('content', models.TextField(verbose_name='질문 내용')),
                ('category', models.CharField(choices=[('1', '일반'), ('2', '계정'), ('3', '기타')], max_length=2, verbose_name='카테고리')),
            ],
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('1', '일반'), ('2', '계정'), ('3', '기타')], max_length=2, verbose_name='카테고리')),
                ('title', models.CharField(max_length=80, verbose_name='질문제목')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='이메일')),
                ('phone', models.CharField(max_length=80, verbose_name='문자메시지')),
                ('is_imail', models.BooleanField(default=False, verbose_name='이메일 수신여부')),
                ('is_phone', models.BooleanField(default=False, verbose_name='문자메시지 수신여부')),
                ('content', models.TextField(verbose_name='문의내용')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='이미지')),
            ],
        ),
    ]
